"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u&-#0$_%a-^#92eas%=6mo*dglz@*p$3zh1__1vh5$xdniuyw='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.analytics.apps.AnalyticsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

import os
from dotenv import load_dotenv

load_dotenv(override=True)

MONGO_URI = os.getenv("MONGO_URI")
# Shared multi-platform analytics database. Keeps its historical name by default
# so existing LinkedIn data is not orphaned; rows carry a ``platform`` field.
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME", "linkedin_db")

LINKEDIN_CLIENT_ID = os.getenv("LINKEDIN_CLIENT_ID")
LINKEDIN_CLIENT_SECRET = os.getenv("LINKEDIN_CLIENT_SECRET")
LINKEDIN_REFRESH_TOKEN = os.getenv("LINKEDIN_REFRESH_TOKEN")
LINKEDIN_ACCESS_TOKEN = os.getenv("LINKEDIN_ACCESS_TOKEN")
LINKEDIN_ORG_ID = os.getenv("LINKEDIN_ORG_ID")
LINKEDIN_API_VERSION = os.getenv("LINKEDIN_API_VERSION", "202604")
LINKEDIN_REQUEST_TIMEOUT = int(os.getenv("LINKEDIN_REQUEST_TIMEOUT", "20"))
LINKEDIN_PAGE_SIZE = int(os.getenv("LINKEDIN_PAGE_SIZE", "100"))

# Dashboard read behavior:
#   DASHBOARD_LIVE_FETCH: when true, /api/linkedin-analytics/?format=dashboard fetches
#   time-bound data live from LinkedIn for the requested window and caches it; when
#   false, it serves only already-synced snapshots from MongoDB.
DASHBOARD_LIVE_FETCH = os.getenv("DASHBOARD_LIVE_FETCH", "true").lower() in ("1", "true", "yes")
DASHBOARD_CACHE_TTL_SECONDS = int(os.getenv("DASHBOARD_CACHE_TTL_SECONDS", str(6 * 3600)))

# Instagram / Meta Graph API (Facebook-Login path). Tokens are stored in MongoDB
# (tokens collection, platform="instagram"); .env provides only the bootstrap
# access token and the app credentials. See docs/instagram-insights-analysis.md.
META_APP_ID = os.getenv("META_APP_ID")
META_APP_SECRET = os.getenv("META_APP_SECRET")
META_REDIRECT_URI = os.getenv("META_REDIRECT_URI")
META_GRAPH_API_VERSION = os.getenv("META_GRAPH_API_VERSION", "v24.0")
META_REQUEST_TIMEOUT = int(os.getenv("META_REQUEST_TIMEOUT", "20"))
META_PAGE_SIZE = int(os.getenv("META_PAGE_SIZE", "100"))
INSTAGRAM_ACCESS_TOKEN = os.getenv("INSTAGRAM_ACCESS_TOKEN")
INSTAGRAM_BUSINESS_ACCOUNT_ID = os.getenv("INSTAGRAM_BUSINESS_ACCOUNT_ID")
# Proactively re-exchange the long-lived Instagram token once it is within this
# many days of its ~60-day expiry (Meta allows extending a still-valid token).
INSTAGRAM_TOKEN_REFRESH_LEAD_DAYS = int(os.getenv("INSTAGRAM_TOKEN_REFRESH_LEAD_DAYS", "7"))

# Platforms the nightly scheduler should sync. Comma-separated; defaults to
# LinkedIn only until the Instagram account/token setup is confirmed live.
ANALYTICS_SYNC_PLATFORMS = [
    p.strip() for p in os.getenv("ANALYTICS_SYNC_PLATFORMS", "linkedin").split(",") if p.strip()
]

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
